/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE clientBaseService PLEASE EDIT ../client.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Client } from '../../domain/svrsample1_db/client';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Client.service.ts
 */

/*
 * SCHEMA DB Client
 *
	{
		claimed: {
			type: 'Boolean'
		},
		claimedinfo: {
			type: 'Custom'
		},
		clientlevel: {
			type: 'String',
			required : true
		},
		clientname: {
			type: 'String',
			required : true
		},
		clientrating: {
			type: 'Decimal'
		},
		clienttype: {
			type: 'String'
		},
		createdby: {
			type: 'Custom'
		},
		datecreated: {
			type: 'Date'
		},
		datedeleted: {
			type: 'Date'
		},
		dateinactive: {
			type: 'Date'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		vendor: [{
			type: Schema.ObjectId,
			required : true,
			ref : "Job"
		}],
	}
 *
 */
@Injectable()
export class ClientBaseService {

    private clientCollection: AngularFirestoreCollection<Client>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.clientCollection = afs.collection<Client>('client');
    }


    // CRUD METHODS

    /**
    * ClientService.create
    *   @description CRUD ACTION create
    *   @param Vendor obj Object to insert
    *
    */
    create(item: Client): Promise<DocumentReference> {
        return this.clientCollection.add(item);
    }

    /**
    * ClientService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id Vendor
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.clientCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * ClientService.findByVendorName
    *   @description CRUD ACTION findByVendorName
    *   @param Objectid key Id of the resource VendorName to search
    *
    */
    findByVendorName(id: string): Observable<any[]> {
        return this.afs.collection('client', ref => ref.where('VendorName', '', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Client;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * ClientService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): AngularFirestoreDocument<Client> {
        return this.afs.doc<Client>('client/' + id);
    }

    /**
    * ClientService.list
    *   @description CRUD ACTION list
    *   @returns ARRAY OF Vendor
    *
    */
    list(): Observable<Client[]> {
        return this.afs.collection('client').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Client;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * ClientService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id Vendor
    *   @returns Vendor
    *
    */
    update(itemDoc: AngularFirestoreDocument<Client>, item: Client): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
