/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE jobBaseService PLEASE EDIT ../job.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Job } from '../../domain/svrsample1_db/job';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Job.service.ts
 */

/*
 * SCHEMA DB Job
 *
	{
		dateposted: {
			type: 'Date'
		},
		jobdescription: {
			type: 'String'
		},
		jobtitle: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		vendor: [{
			type: Schema.ObjectId,
			required : true,
			ref : "Job"
		}],
	}
 *
 */
@Injectable()
export class JobBaseService {

    private jobCollection: AngularFirestoreCollection<Job>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.jobCollection = afs.collection<Job>('job');
    }


    // CRUD METHODS

    /**
    * JobService.findByvendor
    *   @description CRUD ACTION findByvendor
    *   @param Objectid key Id of model to search for
    *
    */
    findByVendor(id: string): Observable<any[]> {
        return this.afs.collection('job', ref => ref.where('vendor', 'array-contains', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Job;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }


    // Custom APIs

}
